//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutobuAsa.Models
{

    public partial class Ruta
    {
        public int id { get; set; }
        public int ciudadOrigen { get; set; }
        public int ciudadDestino { get; set; }
        public decimal km { get; set; }
        public decimal precio { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Ciudad Ciudad1 { get; set; }
    }
}
